fix: Relates to #140. Update React Native to 0.56 (#209)
* fix: Relates to #140. Update React Native to 0.57.8

* fix: Bump CI and required Node.js version in package.json to Node 8

* chore: Update dependencies. Cannot update to reactive-native 0.58.3

* fix: Add @babel/plugin-proposal-class-properties

* chore: Boost version of babel-preset-react-native to 5.0.2

* chore: Update to React Native 0.56 to fix Cannot find module 'setupDevtools' from 'setup.js' error

* fix: Fixes error ReferenceError: regeneratorRuntime is not defined